CREATE DATABASE QUIZ;

USE QUIZ;

CREATE TABLE USUARIO (
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(300) NOT NULL UNIQUE
)

CREATE TABLE CURSO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) UNIQUE NOT NULL,
    DESCRICAO VARCHAR(150)
);
